### ISSUE TITLE
login appears to be broken

### ISSUE THREAD

**Issue by xtina-starr** [artsy/force-merge#16]
![login](https://cloud.githubusercontent.com/assets/5201004/22755644/174964f2-ee12-11e6-86a9-ecf167f00891.gif)

**Comment by kanaabe** [comment]
I initially had this problem too, but once I cleared cookies and tried to replicate again after that, I couldn't.

**Comment by craigspaeth** [comment]
@xtina-starr thanks for logging!! There might have been some session overlap weirdness in sharing cookies. As Kana pointed out clearing cookies or going incognito should sort that out. When the real merge happens it should share the session config from Force, so I'll keep an eye on any issues there. In the meantime closing unless you can repro from an incognito window.
