### ISSUE TITLE
No Images on Auctions Popups

### ISSUE THREAD

**Issue by mdole** [artsy/force-merge#19]
Seeing several popups without images. Not sure how sticky these usually are, but they followed me from the homepage to an article.

![screen shot 2017-02-09 at 1 05 21 pm](https://cloud.githubusercontent.com/assets/5361806/22796562/d25bc38c-eec8-11e6-9a66-b0d63de2fed7.png)

**Comment by mdole** [comment]
Seeing the same thing on staging.artsy.net so maybe it's just a result of the merged version pointing there

**Comment by craigspaeth** [comment]
Yep just a staging issue—pointing to production fixes the thumbnails. Thanks for logging!
