### ISSUE TITLE
iPad fairs overview includes artsy.net menu 

### ISSUE THREAD

**Issue by orta** [artsy/force-merge#20]
![screen shot 2017-02-09 at 1 14 20 pm](https://cloud.githubusercontent.com/assets/49038/22796776/ae062454-eec9-11e6-893e-2508362a955a.png)

**Comment by craigspaeth** [comment]
@orta Quickly emulating Eigen iPad in Chrome it appears to be a bug in Force as well? Can you confirm it's not just merged.artsy.net?
