### ISSUE TITLE
404s from main nav on user account page

### ISSUE THREAD

**Issue by anandaroop** [artsy/force-merge#21]
There's something up with the **About** page link:

- **for a non-logged in user** the "About Artsy" link in the footer works  (by rendering the desktop version of the About page)

- **for a logged-in user** the "About Artsy" link in the footer, as well as the "About Artsy" link in the main nav on the user account page (`/user/edit`), both result in 404s

(In all three cases the "About Artsy" link points to `/about`)

**Comment by anandaroop** [comment]
This also appears to be true for the "Partner with Artsy" link:

- **for a logged-in user** the "Partner with Artsy" link in the main nav on the user account page (`/user/edit`),  results in a 404

**Comment by craigspaeth** [comment]
Thanks Roop! Fix here: https://github.com/artsy/force/pull/838
