### ISSUE TITLE
"Artists You Follow" on Artworks page

### ISSUE THREAD

**Issue by mdole** [artsy/force-merge#22]
Clicking the "Artists You Follow" checkbox on artsy.net/collect results in nothing but greyed-out artworks if you haven't followed any artists. This is consistent with the behavior on the live site though, so might be an issue for the Force repo?

![screen shot 2017-02-09 at 1 37 07 pm](https://cloud.githubusercontent.com/assets/5361806/22797604/defc4798-eecc-11e6-8d25-d6efa01661ce.png)

**Comment by craigspaeth** [comment]
Looks like a staging API issue—something about puma and thread pools. It's fixed when pointing merged.artsy.net to production. Thanks for logging!
