### ISSUE TITLE
Not registering new account when try to follow a fair

### ISSUE THREAD

**Issue by christine-artsy** [artsy/force-merge#23]
created a new account on merged.artsy.net (u: christinetest@gmail.com / pw: ***), and when I tried to follow a fair, it directs me create a new account via the standard onboarding. This was also all done in the same session, I created a new Artsy account and tried to start following the fair and was directed to create an account again when I entered my login credentials.

URL: https://merged.artsy.net/untitled-san-francisco-2017
sign in:
<img width="1273" alt="screen shot 2017-02-09 at 2 34 37 pm" src="https://cloud.githubusercontent.com/assets/17463307/22799803/0cf0b1ea-eed5-11e6-9132-2bb33ba13201.png">
didn't register:
<img width="1115" alt="screen shot 2017-02-09 at 2 34 57 pm" src="https://cloud.githubusercontent.com/assets/17463307/22799824/27a3f42a-eed5-11e6-8dd2-c93a7a4f71c9.png">

I haven't filled out the profile with a name or any saved works, but when I tried to replicate on staging via signing in with the same account, it looked like it worked ok:
<img width="1039" alt="screen shot 2017-02-09 at 2 37 10 pm" src="https://cloud.githubusercontent.com/assets/17463307/22799861/484798c6-eed5-11e6-9682-e78212c95a9b.png">

**Comment by craigspaeth** [comment]
@christine-artsy Mind trying this in an icognito window and letting me know if it still fails?

**Comment by christine-artsy** [comment]
@craigspaeth looks good in incognito!

<img width="1028" alt="screen shot 2017-02-09 at 4 00 36 pm" src="https://cloud.githubusercontent.com/assets/17463307/22802972/ee18a528-eee0-11e6-9c09-b604469bfafa.png">
