### ISSUE TITLE
After QA swap at a DNS level every other day?

### ISSUE THREAD

**Issue by craigspaeth** [artsy/force-merge#4]
This could help force people to use the merged codebase. Would probably need to prepare to set config to point to the new domain and share the session secret.

**Comment by joeyAghion** [comment]
Using DNS to send production traffic to the test app doesn't give us much control over that flow. Clients with long caches will continue using the old route for much longer than the configured TTL, and once we update DNS (even briefly), clients may cache that for longer than we'd want.

Can the apps share a cache? Do they rely on in-memory storage for anything? Just wondering if we can put a simple HAProxy or Nginx instance in front of them as a load-balancer.

**Comment by craigspaeth** [comment]
@joeyAghion They do not rely on in-memory storage and probably could share a cache. A load balancer sounds like a better solution 😁  Thanks for noting, I'll make a new issue to investigate that.
